language: php
addons:
  chrome: stable

php:
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - mkdir -p build/logs
  - mkdir -p build/proxy
  - mkdir -p session
  - phpunit
  - php vendor/bin/behat

after_success:
  - travis_retry php vendor/bin/coveralls -v